#!/bin/bash
# 942 "/usr/include/stdio.h" 3 4
#include <string.h>
# 2 "main.c" 2


# 3 "main.c"
int main()
{
   char nickname[20];
   printf("Enter your Nick name:");
   scanf("%s", nickname);
   printf("%s",nickname);
   return (0);
}

